**Automatidata project**
**Course 4 - The Power of Statistics**

You are a data professional in a data analytics firm, called Automatidata. The current project for their newest client, the New York City Taxi & Limousine Commission (New York City TLC) is reaching its midpoint, having completed a project proposal, Python coding work, and exploratory data analysis.

You receive a new email from Uli King, Automatidata’s project manager. Uli tells your team about a new request from the New York City TLC: to analyze the relationship between fare amount and payment type. You also discover follow-up emails from three other team members: Deshawn Washington, Luana Rodriguez, and Udo Bankole. These emails discuss the details of the analysis. A final email from Luana includes your specific assignment: to conduct an A/B test.

**Course 4 End-of-course project: Statistical analysis**

**The purpose** of this project is to demostrate knowledge of how to prepare, create, and analyze A/B tests.

**The goal** is to apply descriptive statistics and hypothesis testing in Python.

This activity has three parts:

**Part 1:** Imports and data loading

- What data packages will be necessary for hypothesis testing?
**Part 2:** Conduct hypothesis testing

- How did computing descriptive statistics help to analyze the data?

- How did I formulate null hypothesis and alternative hypothesis?

**Part 3:** Communicate insights with Stakeholders

- What key business insight(s) emerged from my A/B test?

- What business recommendations do you propose based on results?

**Conduct an A/B test**
Used Statistics to analyze and interpret data. The activity covers fundamental concepts such as descriptive statistics and hypothesis testing.

**The purpose** of this A/B test is to find ways to generate more revenue for taxi cab drivers.

**Note:** For the purpose of this exercise, assume that the sample data comes from an experiment in which customers are randomly selected and divided into two groups: 1) customers who are required to pay with credit card, 2) customers who are required to pay with cash. Without this assumption, we cannot draw causal conclusions about how payment method affects fare amount.

**The goal** for this A/B test is to sample data and analyze whether there is a relationship between payment type and fare amount. For example: discover if customers who use credit cards pay higher fare amounts than customers who use cash.

This activity has two parts:

**Part 1:** Exploratory data analysis Explore the NYC Taxi dataset with Python using a Jupyter notebook. This includes:

- Computing descriptive statistics
**Part 2:** Hypothesis testing with Python

- Conducting a two-sample hypothesis test

**PACE: Plan**
In this stage, consider the following questions where applicable to complete your code response:

**Question** What is your research question for this data project? Later on, you will need to formulate the null and alternative hypotheses as the first step of your hypothesis test. Consider your research question now, at the start of this task.
**Answer** Research question for this data project: 'Is there a relationship between payment type and fare amount?'

**Imports and data loading**
Packages: pandas, matplotlib, scipy.stats
Functions: stats.ttest_ind,stats.ttest_1samp

In [1]:
#import any relevant packages or libraries
import pandas as pd
import numpy as np
from scipy import stats

In [3]:
#import the dataset
taxi_data = pd.read_csv("2017_Yellow_Taxi_Trip_Data.csv",index_col = 0)
taxi_data.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
24870114,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56
35634249,1,04/11/2017 2:53:28 PM,04/11/2017 3:19:58 PM,1,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80
106203690,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75
38942136,2,05/07/2017 1:17:59 PM,05/07/2017 1:48:14 PM,1,3.70,1,N,188,97,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69
30841670,2,04/15/2017 11:32:20 PM,04/15/2017 11:49:03 PM,1,4.37,1,N,4,112,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80

**PACE: Analyze and Construct**
**Question:** Data professionals use descriptive statistics for Exploratory Data Analysis. How can computing descriptive statistics help you learn more about your data in this stage of your analysis?
**Answer:** Computing descriptive statistics at this stage gives an early, fact‑based understanding of how the dataset behaves before modeling. It turns the raw table into something interpretable by highlighting its central tendencies, variability, and potential problems that aren’t obvious from looking at rows alone.

**Data exploration**
Use descriptive statistics to conduct Exploratory Data Analysis (EDA).

In [7]:
# Get the value count of each payment type
taxi_data['payment_type'].value_counts()

1    15265
2     7267
3      121
4       46
Name: payment_type, dtype: int64

Note: In the dataset, payment_type is encoded in integers:
1: Credit card
2: Cash
3: No charge
4: Dispute
5: Unknown

In [5]:
# descriptive stats code for EDA
taxi_data.describe(include='all')

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
count,22699.000000,22699,22699,22699.000000,22699.000000,22699.000000,22699,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000
unique,NaN,22687,22688,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,07/03/2017 3:45:19 PM,10/18/2017 8:07:45 PM,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,2,2,NaN,NaN,NaN,22600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1.556236,NaN,NaN,1.642319,2.913313,1.043394,NaN,162.412353,161.527997,1.336887,13.026629,0.333275,0.497445,1.835781,0.312542,0.299551,16.310502
std,0.496838,NaN,NaN,1.285231,3.653171,0.708391,NaN,66.633373,70.139691,0.496211,13.243791,0.463097,0.039465,2.800626,1.399212,0.015673,16.097295
min,1.000000,NaN,NaN,0.000000,0.000000,1.000000,NaN,1.000000,1.000000,1.000000,-120.000000,-1.000000,-0.500000,0.000000,0.000000,-0.300000,-120.300000
25%,1.000000,NaN,NaN,1.000000,0.990000,1.000000,NaN,114.000000,112.000000,1.000000,6.500000,0.000000,0.500000,0.000000,0.000000,0.300000,8.750000
50%,2.000000,NaN,NaN,1.000000,1.610000,1.000000,NaN,162.000000,162.000000,1.000000,9.500000,0.000000,0.500000,1.350000,0.000000,0.300000,11.800000
75%,2.000000,NaN,NaN,2.000000,3.060000,1.000000,NaN,233.000000,233.000000,2.000000,14.500000,0.500000,0.500000,2.450000,0.000000,0.300000,17.800000
max,2.000000,NaN,NaN,6.000000,33.960000,99.000000,NaN,265.000000,265.000000,4.000000,999.990000,4.500000,0.500000,200.000000,19.100000,0.300000,1200.290000

We are interested in the relationship between payment type and the total fare amount the customer pays. One approach is to look at the average total fare amount for each payment type.

In [8]:
taxi_data.groupby('payment_type')['total_amount'].mean()

payment_type
1    17.663577
2    13.545821
3    13.579669
4    11.238261
Name: total_amount, dtype: float64

Based on the averages shown, it appears that customers who pay in credit card tend to pay a larger total fare amount than customers who pay in cash. However, this difference might arise from random sampling, rather than being a true difference in total fare amount. To assess whether the difference is statistically significant, conduct a hypothesis test.

**Hypothesis testing**
Before conducting hypothesis test, consider the following questions where applicable to complete code response:

Recall the difference between the null hypothesis and the alternative hypotheses. What are the hypotheses for this data project?
**Answer: Null hypothesis** There is a no difference in average total fare between customers who pay using credit cards and customers who pay cash **Alternative hypothesis:** There is a difference in average total fare between customers who pay using credit cards and customers who pay cash

Goal in this step is to conduct a **two-sample t-test.** Below are the steps for conducting a hypothesis test:

1. State the null hypothesis and the alternative hypothesis
2. Choose a signficance level
3. Find the p-value
4. Reject or fail to reject the null hypothesis

Note: For the purpose of this exercise, hypothesis test is the main component of A/B test.

**$H_0$:** There is no difference in the average total fare amount between customers who use credit cards and customers who use cash.

**$H_1$:** : There is a difference in the average total fare amount between customers who use credit cards and customers who use cash.

Choose 5% as the significance level and proceed with a two-sample t-test.

In [13]:
#Get the payment amount for credit card transaction
credit_card = taxi_data[taxi_data['payment_type'] == 1]['total_amount']
#Get the payment amount for cash transaction
cash = taxi_data[taxi_data['payment_type'] == 2]['total_amount']\

#hypothesis test, A/B test
stats.ttest_ind(a = credit_card, b = cash, equal_var=False )

Ttest_indResult(statistic=20.34644022783838, pvalue=4.5301445359736376e-91)

Since the p-value is extremely small (much smaller than the significance level of 5%), you reject the null hypothesis. You conclude that there is a statistically significant difference in the average total fare amount between customers who use credit cards and customers who use cash.

**PACE: Execute**
**Communicate insights with stakeholders**
In conclusion, ask the following questions:

1. What business insight(s) can you draw from the result of your hypothesis test?
2. Consider why this A/B test project might not be realistic, and what assumptions had to be made for this pedagogical project.
**Exemplar responses:**

1. The key business insight is that Payment method may signal different rider segments and Credit‑card users may generate more revenue per trip.

2. The difference in fare between cash and credit‑card users is real, but it is not necessarily caused by payment method. It reflects deeper behavioral and contextual differences in the rider population.The difference between average card payment fare and cash fare is inflated, because we use the total amount as the comparing variable. But cash fares all have tip values of zero dollar, while card payments have non-zero values. A possible reason for this occurance is because cash tips aren't declared. In turn, this means that we capture tips in one group but not in the other. Instead, one should be comparing the fare_amount column.